### ISSUE TITLE
Set custom interval for opening tabs 

### ISSUE THREAD

**Issue by mat926** [psimonyi/openslowly#10]
I would like to set a custom interval when opening tabs.

**Comment by psimonyi** [comment]
I'm not sure what you mean here.  Do you want a delay between finishing one tab and starting the next?  What is the purpose?  Note that by default Open Bookmarks Slowly will open 6 tabs at a time, but you can change that in the add-on preferences.

**Comment by mat926** [comment]
It means to set a time between opening tabs. I.e I want to open a tab for every 3 seconds.

**Comment by psimonyi** [comment]
Can you describe why that would be a useful feature?  What is the purpose of the delay?

**Comment by mat926** [comment]
> 
> 
> Can you describe why that would be a useful feature? What is the purpose of the delay?

The current rate at which it opens tabs would be too fast for older machines, and would cause Firefox to be unresponsive, especially if you're opening many tabs.  Being able to adjust the delay would greatly help.

**Comment by psimonyi** [comment]
If you set the preference for "Maximum number of tabs to load at once" to 1, it will wait for each tab it opens to load completely before starting the next one.  If your computer is unresponsive while loading one web page, I don't see how adding a delay time is going to improve matters.

It almost sounds as if you think this extension already has a timed delay and you want to adjust it.  Note that there *is no timed delay*.  Instead the extension keeps track of the tabs it opens until they finish loading, so that only a few (by default 6) tabs are loading at a time, no matter how many bookmarks are scheduled to be opened.  So if you try opening the same bookmarks on a fast computer and a slow computer, the fast computer will open new tabs much faster because the tabs finish loading faster.

Most computers these days should be able to handle loading 6 tabs at a time.  But if you have a particularly slow one or slow internet, reducing the number of tabs that can be loading at once will help keep Firefox responsive while it's working.  Try setting it to 1 or 2.

**Comment by ghost** [comment]
If a site has really zealous DDoS protection, adding a delay in Open Bookmarks Slowly *might* be useful.

I was trying to open a list of 24 bookmarks in new tabs.  All of them went to the same site that has DDoS protection/rate throttling.  With Firefox's default behavior of opening all of them immediately, some of them loaded correctly, and some of them got me the site's "please try later" page, because I tripped the DDoS protection.

With the default setting in OBS of loading 6 tabs at once, the site worked correctly; all 24 tabs loaded and I never got the "please try later" page.

My *guess* is that if opening 6 tabs at a time was still tripping a site's protection, then turning OBS down to 1 tab at a time would satisfy the site, for nearly all sites.

If a site is enforcing very long waits between loading links, it would probably interfere with "normal" interactive use of the site - a user clicking links on that site as they navigate around.  So, adding additional delay in OBS might not be useful very often, but that's the case I can think of.

Thanks for the extension!

**Comment by psimonyi** [comment]
Thanks.  I agree, it seems technically possible but pretty highly unlikely.  And adding a time delay would only really affect things when it's already set to max 1 tab at a time, which really should be acceptable for any site or old, slow computer.

I'm assuming reporter was speculating about possible problems rather than describing a problem they actually had, and misunderstood how the extension works.

So I am closing this issue for now, but if you find a real problem case, feel free to reopen or file another bug.
