### ISSUE TITLE
Open bookmarks recursively 

### ISSUE THREAD

**Issue by mat926** [psimonyi/openslowly#8]
Could you have it open every bookmark in a folder, including those inside subfolders?

**Comment by psimonyi** [comment]
It's an interesting idea, and one I've thought about before.  But it breaks consistency with Firefox's built-in "open all in tabs" feature, and I'm not sure you'd always want it — probably you'd want it for some folders and not others.  So it's not clear how such a feature should work.

Since you can have multiple slow-open operations running at once and they share the same limit on how many tabs to open at once, there's not much difference between a recursive open and just clicking a few extra times to open each folder.

I'd be interested to hear your thoughts and why you think this would be useful.

**Comment by BUZZARDGTA** [comment]
Please add this, and make it in option in the settings of the extension...
